### ISSUE TITLE
case-insensitive shortnames

### ISSUE THREAD

**Issue by guzzisti** [flokX/devShort#14]
Currently the short names are case-sensitive, creating a shortlink named "Test" leads to a 404 if you use "test" in your URI.

Case-sensitivity may be relevant when using "hashed" sthortnames (like "bit.ly/5hJkd"), but from my point of view for user-defined shortnames i'd expect the shortnames to be case-insensitive.

What do you think about it?
May this be worth an additional setting or could be changed in general?

**Comment by guzzisti** [comment]
i've made a KISS-version for my own use: https://github.com/flokX/devShort/compare/master...guzzisti:case-insensitive-urls

Feel free to pull this in if you like.

**Comment by flokX** [comment]
I thought about this design change a long time, but in the end I think it's a good solution because it makes the shortening more intuitive.
