### ISSUE TITLE
re-create already existing shortname

### ISSUE THREAD

**Issue by guzzisti** [flokX/devShort#15]
If i "recreate" a shortname that already exists, the settings are overwritten with the new url and the stats for this shortname are reset.
There's no warning or hint that the name already exists.

My expectation is, that i'm at least warned that i gonna wipe an existing shortlink. Maybe it's even better to avoid this entirely, so that a shortname has to be deleted first.

Whats your view on this?

**Comment by flokX** [comment]
Welcome to the devShort project! Thank you for your issues and PRs. I would be pleased if you would comment on the current PR #18.

You are totally true about this issue. To be honest, I never really thought about this problem.

Currently there is already a feedback when the URL is on the server side considered as invalid so I think it's not a great deal to add this.

I would prefer to block the addition completely, as the user can simply remove the old shortlink before.

**Comment by guzzisti** [comment]
> I would prefer to block the addition completely, as the user can simply remove the old shortlink before.

I'm fine with that :+1:
