### ISSUE TITLE
Cannot see any charts on the demo, 401 error on JSON file request

### ISSUE THREAD

**Issue by nodiscc** [flokX/devShort#8]
From https://github.com/Kickball/awesome-selfhosted/pull/1682 :

> It would be cool if the demo had some pre-generated shortlinks to see what the tool looks like in real usage. Or maybe it's a problem on my side? (I can't see any links/charts and have a SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data error in the browser console)

On further investigation I get a 401 error while fetching https://devshort.florian-kaldowski.de/admin/stats.json. I have disabled HTTPS Everywhere and the problem persists.

**Comment by flokX** [comment]
Thank you for the error code.
I slightly changed the code of the demo.

Please check the demo page again. If it still doesn't work, please tell me which browser and operating system you are using.

**Comment by flokX** [comment]
Forgot that it would close the issue, still waiting for the feedback if it works.

**Comment by nodiscc** [comment]
Works fine, good job
